# Cambodia

```{r}
#| label: Cambodia-loading
#| include: false
source("R/load-all.r")
cambodia_lyrs <- country_map_lyrs("Cambodia")
```

## Project-904

```{r}
#| label: fig-Cambodia-904
#| fig.cap: !expr paste0("Cambodia-Project-904 synthetic control; comprising ", proj_904_count$n_weighted, " donors from a potential pool of ", proj_904_count$n_pot, " donors. The donor pool subset is based on a buffer deforestation threshold value of ", proj_904_donors_l$cutoff)
#| echo: false
#| message: false
#| warning: false
#| results: hide

project_904 <- west_extract_proj_area(cambodia_lyrs$country_sc_sp, 904)

proj_904_donors_l <- sc_wrap_recursive(
  filepath = cambodia_lyrs$country_csv,
  dbf_file = cambodia_lyrs$country_dbf,
  project_id = 904,
  project_start_date = 2008,
  project_name = "Cambodia 904",
  predictors_list = c(
    "tree", "pa", "slope", "dem", "mine", "soil", "conces", "fric", "def",
    "defc", "mm", "buf10k_def", "buf10k_defc"
  ),
  drop_controls = c(),
  cutoff_start = 0.3
)

proj_904_count <- count_donors(proj_904_donors_l)

proj_904_donors <- proj_904_donors_l |>
  locate_donors(cambodia_lyrs$country_sc_sp)

```

```{r}
#| label: fig-Cambodia-904-map
#| fig-cap: "Cambodia-Project-904 synthetic control map"
#| echo: false
#| message: false
#| warning: false
donor_leaf_map(
  proj_donors = proj_904_donors,
  country_spat = cambodia_lyrs$country,
  country_name = "Cambodia",
  project_area = project_904,
  proj_num = 904,
  ecoregions = cambodia_lyrs$ecoregions,
  states = cambodia_lyrs$states
)
```


## Project-1650

```{r}
#| label: fig-Cambodia-1650
#| fig.cap: !expr paste0("Cambodia-Project-1650 synthetic control; comprising ", proj_1650_count$n_weighted, " donors from a potential pool of ", proj_1650_count$n_pot, " donors. The donor pool subset is based on a buffer deforestation threshold value of ", proj_1650_donors_l$cutoff)
#| echo: false
#| message: false
#| warning: false
#| results: hide

project_1650 <- west_extract_proj_area(cambodia_lyrs$country_sc_sp, 1650)

proj_1650_donors_l <- sc_wrap_recursive(
  filepath = cambodia_lyrs$country_csv,
  dbf_file = cambodia_lyrs$country_dbf,
  project_id = 1650,
  project_start_date = 2010,
  project_name = "Cambodia 1650",
  predictors_list = c(
    "tree", "pa", "slope", "dem", "mine", "soil", "conces", "fric", "def",
    "defc", "mm", "buf10k_def", "buf10k_defc"
  ),
  drop_controls = c(),
  min_donors = 1
)

proj_1650_count <- count_donors(proj_1650_donors_l)

proj_1650_donors <- proj_1650_donors_l |>
  locate_donors(cambodia_lyrs$country_sc_sp)

```

```{r}
#| label: fig-Cambodia-1650-map
#| fig-cap: "Cambodia-Project-1650 synthetic control map"
#| echo: false
#| message: false
#| warning: false

donor_leaf_map(
  proj_donors = proj_1650_donors,
  country_spat = cambodia_lyrs$country,
  country_name = "Cambodia",
  project_area = project_1650,
  proj_num = 1650,
  ecoregions = cambodia_lyrs$ecoregions,
  states = cambodia_lyrs$states
)
```
